# Generated by Django 4.0.9 on 2023-06-15 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('nieaktywny', 'nieaktywny'), ('aktywny', 'aktywny')], default='aktywny', max_length=30)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d', verbose_name='Fotografia')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Data urodzenia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
