# Generated by Django 4.0.9 on 2023-06-15 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Gmina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('wojt', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(blank=True, max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=55)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Miejscowosc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('profil', models.CharField(choices=[('miasto', 'Miasto'), ('wieś', 'Wieś')], default='miasto', max_length=30)),
                ('gmina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miejscowosci', to='eshop.gmina')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250)),
                ('nazwa_prod', models.CharField(blank=True, max_length=250)),
                ('nazwa_english', models.CharField(blank=True, max_length=250)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('cena_brutto', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('stock', models.PositiveIntegerField(blank=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('width', models.PositiveIntegerField(blank=True)),
                ('long', models.PositiveIntegerField(blank=True)),
                ('weight', models.PositiveIntegerField(blank=True)),
                ('vendor_code', models.CharField(blank=True, max_length=40)),
                ('article_at', models.CharField(blank=True, max_length=40)),
                ('kod_cn', models.CharField(blank=True, max_length=40)),
                ('pkwiu', models.CharField(blank=True, max_length=40)),
                ('eps', models.CharField(blank=True, max_length=240)),
                ('cena_prod', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('cena_our', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('origin_code', models.CharField(blank=True, max_length=40)),
                ('cecha1', models.CharField(blank=True, max_length=40)),
                ('cecha2', models.CharField(blank=True, max_length=40)),
                ('cecha3', models.CharField(blank=True, max_length=40)),
                ('kategoria', models.CharField(choices=[('traktory', 'traktory'), ('kombajny', 'kombajny'), ('siewniki mechaniczne', 'siewniki mechaniczne'), ('siewniki pneumatyczne', 'siewniki pneumatyczne'), ('aparat koszący zboże', 'aparat koszący zboże'), ('aparat koszący kukurydzy', 'aparat koszący kukurydzy'), ('ładowarki teleskopowe', 'ładowarki teleskopowe'), ('kombajn do paszy', 'kombajn do paszy'), ('spryskiwacze', 'spryskiwacze'), ('prasy', 'prasy'), ('kultywatory', 'kultywatory'), ('brony talerzowe', 'brony talerzowe'), ('pługi', 'pługi'), ('rolnicze', 'rolnicze'), ('budowlane', 'budowlane')], default='traktory', max_length=30)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('aktywny', 'aktywny'), ('ban', 'ban')], default='aktywny', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='eshop.category')),
            ],
            options={
                'ordering': ('created',),
                'index_together': {('id', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Wojewodztwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('wojewoda', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Technikalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zamiennik', models.TextField(blank=True)),
                ('zastosowanie', models.TextField(blank=True)),
                ('produkt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technikalias', to='eshop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Powiat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('starosta', models.CharField(blank=True, max_length=50)),
                ('wojewodztwo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='powiatos', to='eshop.wojewodztwo')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(blank=True, max_length=30)),
                ('nazwisko', models.CharField(blank=True, max_length=50)),
                ('adres', models.CharField(blank=True, max_length=60)),
                ('kodpocztowy', models.CharField(blank=True, max_length=6)),
                ('stanowisko', models.CharField(choices=[('prezes zarządu', 'prezes zarządu'), ('członek zarządu', 'członek zarządu'), ('prokurent', 'prokurent'), ('właściciel', 'właściciel'), ('udziałowiec', 'udziałowiec'), ('akcjonariusz', 'akcjonariusz'), ('dyrektor', 'dyrektor'), ('handlowiec', 'handlowiec'), ('przedstawiciel handlowy', 'przedstawiciel handlowy'), ('dyrektor handlowy', 'dyrektor handlowy'), ('dyrektor finansowy', 'dyrektor finansowy'), ('dyrektor produkcji', 'dyrektor produkcji'), ('dyrektor marketingu', 'dyrektor marketingu'), ('główny księgowy', 'główny księgowy'), ('pracownik', 'pracownik'), ('brak', 'brak')], default='dyrektor', max_length=60)),
                ('kom', models.CharField(blank=True, max_length=18, verbose_name='telefon komórkowy')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('instagram', models.URLField(blank=True)),
                ('shortopis', models.CharField(blank=True, max_length=200, verbose_name='krótki opis')),
                ('opis', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('miejscowosc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='personas', to='eshop.miejscowosc')),
            ],
            options={
                'verbose_name': 'osoba',
                'verbose_name_plural': 'osoby',
                'ordering': ('nazwisko',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=210)),
                ('image', models.ImageField(blank=True, upload_to='products/%y/%m/%d')),
                ('opis', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagesy', to='eshop.kategoria')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='eshop.product')),
            ],
        ),
        migrations.AddField(
            model_name='gmina',
            name='powiat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gminas', to='eshop.powiat'),
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(blank=True, max_length=40, unique=True, verbose_name='nazwa unikalna')),
                ('slug', models.SlugField(blank=True)),
                ('firma', models.CharField(blank=True, max_length=80, verbose_name='nazwa handlowa')),
                ('adres', models.CharField(blank=True, max_length=60, null=True)),
                ('kod_pocztowy', models.CharField(blank=True, max_length=6)),
                ('tel', models.CharField(blank=True, max_length=18)),
                ('fax', models.CharField(blank=True, max_length=18)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('www', models.URLField(blank=True)),
                ('status_prawny', models.CharField(choices=[('działalność', 'Jednoosobowa działalność gospodarcza'), ('spółka cywilna', 'Spółka cywilna'), ('spółka jawna', 'Spółka jawna'), ('spółka komandytowa', 'Spółka komandytowa'), ('spółka zoo', 'Spółka z.o.o'), ('spółka akcyjna', 'Spółka akcyjna'), ('gmbh', 'GmbH'), ('ltd', 'Ltd'), ('inna', 'Inna'), ('brak', 'Brak'), ('osoba fizyczna', 'Osoba fizyczna')], default='brak', max_length=60)),
                ('nip', models.CharField(blank=True, max_length=10)),
                ('rodzaj_ewidencji', models.CharField(choices=[('krs', 'KRS'), ('ceidg', 'CEIDG'), ('inne', 'Inne'), ('brak', 'Brak')], default='brak', max_length=20)),
                ('nr_w_ewidencji', models.CharField(blank=True, max_length=20)),
                ('regon', models.CharField(blank=True, max_length=9)),
                ('kapital', models.DecimalField(decimal_places=0, default=5000, max_digits=12, verbose_name='kapitał zakładowy')),
                ('konto_bankowe', models.CharField(blank=True, max_length=34)),
                ('shortopis', models.CharField(blank=True, max_length=200, verbose_name='krótki opis')),
                ('opis', models.TextField(blank=True)),
                ('kategoria', models.CharField(choices=[('produkcja rolna', 'produkcja rolna'), ('hurtownia części', 'hurtownia części'), ('sklep części', 'sklep części'), ('serwis maszyn', 'serwis maszyn'), ('usługi sprzętowe', 'usługi sprzętowe'), ('inne', 'inne')], default='inne', max_length=20)),
                ('status', models.CharField(choices=[('aktywny', 'aktywny'), ('ban', 'ban')], default='aktywny', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stan', models.CharField(choices=[('klient', 'klient'), ('kontakt', 'kontakt')], default='klient', help_text='Czy jest klientem lub potencjalnym klientem dla projektu?', max_length=20)),
                ('miejscowosc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='klientoso', to='eshop.miejscowosc')),
                ('osoba_kontaktowa', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='klientos', to='eshop.persona')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
        migrations.CreateModel(
            name='Dzielnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('miejscowosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dzielnicas', to='eshop.miejscowosc')),
            ],
            options={
                'ordering': ('nazwa',),
            },
        ),
    ]
